### ISSUE TITLE
base.cpp:82:16: error: ‘invalid_argument’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Shufang-Zhu** [whitemech/lydia#114]
Trying to build Lydia on Ubuntu 21.04, gcc 10.3.0

`lydia/lib/src/logic/ltlf/base.cpp:82:16: error: ‘invalid_argument’ is not a member of ‘std’
   82 |     throw std::invalid_argument("LTLfAnd formula: arguments must be > 1");
      |                ^~~~~~~~~~~~~~~~
`

Adding `#include <stdexcept>` to base.cpp would fix the bug.

**Comment by marcofavorito** [comment]
Closed by #115
