### ISSUE TITLE
something wrong with the demo "examples/counter_1.ltlf" in README

### ISSUE THREAD

**Issue by Tridu33** [whitemech/lydia#121]
**Describe the bug**
i run this demo in 'readme.md':
```bash
/lydia$ lydia -l ltlf -f examples/counter_1.ltlf --part examples/counter_1.part
[2022-01-10 21:39:19.438] [lydia] [info] [main] Parsing "examples/counter_1.ltlf"
COError: syntax error at 1.5
Parse failed!
```
maybe somethig wrong in the "examples/counter_1.ltlf", and how can I fix it?

--------------------------------------------------------------------------

By the way, maybe it can add some suggestions for installation, for me, I add this into "CMakeList.txt" can help.

```cmake
# cudd
set (CUDD_LIBRARIES /home/tridu33/cudd/lib/libcudd.a)
set (CUDD_INCLUDE_DIRS /home/tridu33/cudd/include)
set (MONA_INCLUDE_DIRS /usr/include/mona)
# for 'cppitertools',in bash i  do this:
#  "export CPLUS_INCLUDE_PATH=/mnt/host/d/ltlsynthesis/lydia/third_party/cppitertools:$CPLUS_INCLUDE_PATH"
message(">>> SET DEFAULT TO BEFORE, include_dirs=${dirs}")
```

------------------------------------------------------------------------

also, when i built Syft+, after `make install`, 
```bash
$ ls /usr/local/bin
Syft  ltlf2fol  lydia
```
when i call "Syft --help" , it shows that "./ltlf2fol NOT FOUND", then i need to do this:
change this:
```cpp
string LTLF2FOL = "./ltlf2fol NNF "+LTLFfile+" >"+FOL;
```
to this:
```cpp
string LTLF2FOL = "ltlf2fol NNF "+LTLFfile+" >"+FOL;
```

in line 8 of `syft\src\synthesis\main.cpp`.

**Comment by ami-sakakibara** [comment]
I encountered the same issue. I guess this is because the upper-case alphabets are not acceptable to define symbols. I found the following code in `parser/ltlf/lexer.l`:
```
[a-z_][a-z0-9_]*|(\"[^\"\t\r\n]+\")|(\'[^\'\t\r\n]+\') {
                                yylval->symbol_name = yytext;
                                return token::SYMBOL;
                            }
```


I tried transforming the symbol representations from upper case to lower case, which worked without parsing errors.
